name: pass-policy-service Continuous Integration
on: [ pull_request, workflow_dispatch ]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  print-workflow-description:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a CI build of branch ${{ github.ref }} in repository ${{ github.repository }}"
      - run: echo "This job was triggered by a ${{ github.event_name }} event and is running on a ${{ runner.os }} server"

  run-unit-tests:
    name: "Run Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: Run Unit Tests
        run: go test ./...
    
  run-integration-tests:
    name: "Run Integration Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: Docker pull
        run: docker-compose pull

      - name: Start containers
        run: docker-compose up -d

      - name: Run Integration Tests
        run: go test -tags=integration ./...

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
